plugins {
    id "application"
}
apply plugin : "java" 

application {
    mainClassName = "main.java.gui.RobotsProgram"
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}

dependencies {
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.13.0'
    
    testImplementation 'org.junit.jupiter:junit-jupiter:5.13.4'
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testImplementation 'org.mockito:mockito-core:5.4.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.4.0'
    // testImplementation 'org.testcontainers:junit-jupiter:1.19.3'
}
